# Numpy

Numerical Python  - Open source Python library thats used in almost every field of science and engineering.

* ndarray, an efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.
* Math functions for fast operations on entire arrays of data without having to write loops
* Tools for reading/writing array data to disk and working with memory-mapped files
* Linear algebra, random number generation and Fourier transform capablities
* A "C" API for connecting NumPy with libraries written in C, C++ or Fortran

In [1]:
import numpy as np

In [2]:
# Create an array object

arr = np.array([[1,2,3],[4,2,5]])

print("Type ", type(arr))
print("Dimensions ", arr.ndim)
print("Shape ", arr.shape)
print("Size ", arr.size)
print("Data type stored ", arr.dtype)

Type  <class 'numpy.ndarray'>
Dimensions  2
Shape  (2, 3)
Size  6
Data type stored  int64


## Attributes of an array

Fixed size container of items of the same type and size

The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension

In NumPy, dimensions are called axes.

`[0.,0.,0.], [1.,1.,1.]]`
This array has 2 axes. First axis has a length of 2 and second axis has a length of 3.

### NumPy Ndarray

In [8]:
arr3 = np.arange(24).reshape(2,3,4)

In [9]:
arr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [10]:
print(arr3)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [11]:
#accessing 3D objects
print(arr3[1]) #what is stored at index 1
print(arr3[1][2]) #what is stored at index 1 and index 2
print(arr3[1][2][2]) #what is stored at index 1 and index 2

print(arr3.shape)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[20 21 22 23]
22
(2, 3, 4)


### 3-D Array

In [12]:
import numpy as np

my3DArray = np.array([[[1,2,3], [4,5,6], [7,8,9]],
                    [[10,11,12], [13,14,15], [16,17,18]], 
                    [[19,20,21], [22,23,24], [25,25,27]]
                   ])
display(my3DArray)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 25, 27]]])

## Indexing and Slicing

In [13]:
data = np.array([1,2,3])
data[1]

np.int64(2)

In [14]:
data[0:2]

array([1, 2])

In [15]:
data[1:]

array([2, 3])

In [16]:
data[-2:]

array([2, 3])

### Array Slicing

In [19]:
a = np.arange(36).reshape(6,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [20]:
a[0,3:5]

array([3, 4])

In [21]:
a[4:,4:]

array([[28, 29],
       [34, 35]])

In [22]:
a[:2]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### Strides are also possible

In [23]:
a[2::2,::2]

array([[12, 14, 16],
       [24, 26, 28]])

### 3D Array

In [25]:
my3DArray = np.array([[[1,2,3], [4,5,6], [7,8,9]],
                    [[10,11,12], [13,14,15], [16,17,18]], 
                    [[19,20,21], [22,23,24], [25,25,27]]
                   ])
display(my3DArray)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 25, 27]]])

In [26]:
my3DArray[1,1,1]

np.int64(14)

In [27]:
my3DArray[2,1,2]

np.int64(24)

### Coding in class:

In [28]:
import numpy as np

arr1 = np.arange(3)
arr1
print(arr1)
#[0 1 2]
print()
#accessing 1D objects
print(arr1[1]) #what is stored at index 1

arr2 = np.arange(9).reshape(3,3)
arr2
print(arr2)
print()
#accessing 2D objects
print(arr2[1]) #what is stored at index 1
print(arr2[1][2]) #what is stored at index 1 and index 2

arr3 = np.arange(27).reshape(3,3,3)
arr3
print(arr3)
print()

#accessing 3D objects
print(arr3[1]) #what is stored at index 1
print(arr3[1][2]) #what is stored at index 1 and index 2
print(arr3[1][2][2]) #what is stored at index 1 and index 2

print(arr3.shape)

[0 1 2]

1
[[0 1 2]
 [3 4 5]
 [6 7 8]]

[3 4 5]
5
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[15 16 17]
17
(3, 3, 3)


## Numpy is faster than built-in python list

In [30]:
my_arr = np.arange(1000000) 
my_list = list(range(1000000))

"Now let’s multiply each sequence by 2:"
 
#run it 10 times
%time for _ in range(10): my_arr2 = my_arr * 2 
%time for _ in range(10): my_list2 = [x * 2 for x in my_list] 

display(my_arr2)
display(my_list2)

CPU times: total: 31.2 ms
Wall time: 96 ms
CPU times: total: 562 ms
Wall time: 1.11 s


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

# NumPy ndarray: Multidimensional Array object

In [31]:
# Generate some random data 
data = np.random.randn(2,3)

In [32]:
data

array([[ 2.03814137, -0.2948862 , -2.58238118],
       [ 1.33273768, -1.6378884 , -0.01917086]])

In [33]:
data*10

array([[ 20.38141366,  -2.94886198, -25.82381183],
       [ 13.32737675, -16.37888402,  -0.19170861]])

In [34]:
data + data

array([[ 4.07628273, -0.5897724 , -5.16476237],
       [ 2.66547535, -3.2757768 , -0.03834172]])

In [35]:
data.shape

(2, 3)

In [36]:
data.dtype

dtype('float64')

In [37]:
display(data.ndim)

2

## Similarities between python list and NumPy array

In [38]:
list = [1,2,3]
list

[1, 2, 3]

In [39]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [40]:
list[0] = 0 # Mutuable
list

[0, 2, 3]

In [41]:
arr[0] = 0 # Mutuable
arr

array([0, 2, 3])

### Indexing

In [42]:
list[2]

3

In [43]:
arr[2]

np.int64(3)

### Slicing

In [44]:
list[:2]

[0, 2]

In [45]:
arr[1:]

array([2, 3])

## Difference between Python list and NumPy Array

### List canot directly handle a mathematical operations, while array can

In [46]:
list = [0,1,2]
list*2

[0, 1, 2, 0, 1, 2]

In [47]:
arr = np.array([0,1,2])
arr*2

array([0, 2, 4])

In [48]:
# TO use multiplication in list, use numpy library
np.multiply(list,2)

array([0, 2, 4])

### Array consumes less memory than a list

In [49]:
import sys
aList2 = [1,2,3,4,5,6,7,8,9,0,11,12,13,14]
display(sys.getsizeof(aList2))


arr = np.array([1,2,3,4,5,6,7,8,9,0,11,12,13,14])
display(sys.getsizeof(arr))


168

224

## Comparison between Numpy array and Python list

In [50]:
# importing numpy package
import numpy as np

# importing system module
import sys

# declaring a list of 1000 elements
S= range(1000)

# printing size of each element of the list
print("Size of each element of list in bytes: ",sys.getsizeof(S))

# printing size of the whole list
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))

# declaring a Numpy array of 1000 elements
D= np.arange(1000)

# printing size of each element of the Numpy array
print("Size of each element of the Numpy array in bytes: ",D.itemsize)

# printing size of the whole Numpy array
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)



Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000


## Creating ndarrays

In [51]:
data1 = [6, 7.5, 8, 0, 1] 
arr1 = np.array(data1) 


In [52]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [53]:
type(arr1)

numpy.ndarray

In [54]:
arr1.shape

(5,)

In [55]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] 
arr2 = np.array(data2) 
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
arr2.ndim

2

In [57]:
arr2.shape

(2, 4)

In [58]:
arr1.dtype

dtype('float64')

In [59]:
arr2.dtype

dtype('int64')

## Creating ndarrays - with zeros

In [60]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## Creating ndarrays - with empty

In [62]:
np.empty((2,3,2))

array([[[1.07730247e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.01855798e-312, 5.74084271e+169]],

       [[7.17475515e-091, 1.17713279e-047],
        [8.46266866e+164, 7.86788084e-067],
        [3.99910963e+252, 1.36230321e+161]]])

## Exercises

Creating an array

In [63]:
dataSingle = [1, 2, 3, 4]
dataSingleArray = np.array(dataSingle) 
display(dataSingleArray)
dataSingleArray.shape

dataSingleArray[2]

array([1, 2, 3, 4])

np.int64(3)

In [64]:
# Creating a 2d array

data2D = [[1, 2, 3, 4], [5,6,7,8]]
data2DArray = np.array(data2D) 
display(data2DArray)
data2DArray.shape
data2DArray[1, 1]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

np.int64(6)

In [65]:
# Creating a 3d array

data3D = [[1, 2, 3, 4], [5,6,7,8]],[[9,10,11,12], [13,14,15,16]],[[17,18,19,20], [21,22,23,14]]
data3DArray = np.array(data3D) 
display(data3DArray)
display(data3DArray.shape)

#how to get 19 out
data3DArray[2,0,2]


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 14]]])

(3, 2, 4)

np.int64(19)

## Data Types for ndarrays

In [66]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [67]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [68]:
arr1.dtype

dtype('float64')

In [69]:
arr2.dtype

dtype('int32')

### Explicitly convert one type to another

In [70]:
arr = np.array([1, 2, 3, 4, 5]) 
print(arr.dtype) 
float_arr = arr.astype(np.float64) 
print(float_arr.dtype)

int64
float64


In [72]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1]) 
print(arr) 
arr.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [78]:
try:
    numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
except AttributeError: # np.string_ is deprecated...
    numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.bytes_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

# Broadcasting

Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes

In [79]:
data = np.array([1.0,2.0])
data * 1.6

array([1.6, 3.2])

In [80]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr


array([[1., 2., 3.],
       [4., 5., 6.]])

In [82]:
arr * arr


array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [84]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [85]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [86]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [87]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [88]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

# Using Matplotlib with NumPy

In [89]:
#import all the necessary libraries
import numpy as np
import matplotlib.pyplot as plt

#defining a user-defined function to plot the three-dimensional scatter plot
def three_dimensional_scatter(x1,y1,z1,x2,y2,z2):
    #creating figure object in the plot
    fig = plt.figure(figsize = (9,9))
    #created three-dimensional workspace 
    ax = fig.add_subplot(111, projection='3d')
    #plotting the first three-dimensional scatter plot using the parameters 
    ax.scatter3D(x1, y1, z1, color = "green")
    #plotting the second three-dimensional scatter plot using the parameters
    ax.scatter3D(x2, y2, z2, color = "red")
    #defining title to the plot
    plt.title("Creating three-dimensional scatter plot using matplotlib and numpy")
    #defining legends to the plot
    plt.legend(["first","second"])
    #displaying the three-dimensional scatter plot
    plt.show()
    
#creating the main() function
def main():
    #creating data points for the z-axis
    z1 = np.arange(0,150,1)
    #creating data points for the x-axis
    x1 = np.random.randint(8000, size =(150))
    #creating data points for the y axis
    y1 = np.random.randint(800, size =(150))
    z2 = np.arange(0,150,1)
    #creating data points for the x-axis
    x2 = np.random.randint(8000, size =(150))
    #creating data points for the y axis
    y2 = np.random.randint(800, size =(150))
    #calling the main() function
    three_dimensional_scatter(x1,y1,z1,x2,y2,z2)

#declaring the main() function as the driving code of the program.
if __name__ == "__main__":
    main()


## Basic Slicing and indexing

In [90]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
arr[5]

np.int64(5)

In [92]:
arr[5:8]

array([5, 6, 7])

In [93]:
arr[5:8] = 12

In [94]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [95]:
arr_slice = arr[5:8] 

In [96]:
arr_slice

array([12, 12, 12])

In [97]:
aList = [1,2,3,4,5,6,7,8,9]
aSlice = aList[2:6]
print(aSlice)
aSlice[1] = 999
print(aSlice)
print(aList)

[3, 4, 5, 6]
[3, 999, 5, 6]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


### Copy slice into another address



In [98]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)
arr_slice = arr[5:8].copy()
print(arr_slice) 
arr_slice[1:3] = 222
print(arr_slice)
print(arr)

5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12]
[ 12 222 222]
[ 0  1  2  3  4 12 12 12  8  9]


In [100]:
# 2D - array
# ---------------
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print(arr2d.ndim)
print(arr2d.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [102]:
arr2d[2]

array([7, 8, 9])

In [103]:
arr2d[0][2]

np.int64(3)

In [104]:
arr2d[0,2]

np.int64(3)

In [105]:
# 3D array
# ---------------
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d.ndim)
print(arr3d.shape)

3
(2, 2, 3)


In [106]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [108]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [109]:
arr3d[1,0]

array([7, 8, 9])

In [112]:
x = arr3d[1]

In [113]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [114]:
x[0]

array([7, 8, 9])

# Boolean indexing

In [115]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [116]:
data = np.random.randn(7, 4)

In [117]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [118]:
data

array([[-0.28780306,  0.26532538,  0.99569919,  0.97705351],
       [-1.48750655,  1.15735167, -0.06347258, -0.49902649],
       [ 0.9801328 , -0.22844806, -1.02410546,  0.26089841],
       [ 0.92633444,  0.66699548,  1.03300605, -0.24667503],
       [-0.90030978, -0.46910362,  0.21295563,  0.58592052],
       [ 0.44930027,  0.34649884, -0.23300257, -1.1563258 ],
       [-0.26677657,  1.01505676,  0.21991545,  0.24546237]])

In [120]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [121]:
data[names=="Bob"]

array([[-0.28780306,  0.26532538,  0.99569919,  0.97705351],
       [ 0.92633444,  0.66699548,  1.03300605, -0.24667503]])

In [122]:
data[names=="Bob", 2:]

array([[ 0.99569919,  0.97705351],
       [ 1.03300605, -0.24667503]])

In [123]:
data[names=="Bob", 3]

array([ 0.97705351, -0.24667503])

In [124]:
# To select everything but "Bob"
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [125]:
data[~(names == 'Bob')]

array([[-1.48750655,  1.15735167, -0.06347258, -0.49902649],
       [ 0.9801328 , -0.22844806, -1.02410546,  0.26089841],
       [-0.90030978, -0.46910362,  0.21295563,  0.58592052],
       [ 0.44930027,  0.34649884, -0.23300257, -1.1563258 ],
       [-0.26677657,  1.01505676,  0.21991545,  0.24546237]])

In [126]:
cond = names == "Bob"
data[~cond]

array([[-1.48750655,  1.15735167, -0.06347258, -0.49902649],
       [ 0.9801328 , -0.22844806, -1.02410546,  0.26089841],
       [-0.90030978, -0.46910362,  0.21295563,  0.58592052],
       [ 0.44930027,  0.34649884, -0.23300257, -1.1563258 ],
       [-0.26677657,  1.01505676,  0.21991545,  0.24546237]])

In [127]:
data[data < 0] = 0
data

array([[0.        , 0.26532538, 0.99569919, 0.97705351],
       [0.        , 1.15735167, 0.        , 0.        ],
       [0.9801328 , 0.        , 0.        , 0.26089841],
       [0.92633444, 0.66699548, 1.03300605, 0.        ],
       [0.        , 0.        , 0.21295563, 0.58592052],
       [0.44930027, 0.34649884, 0.        , 0.        ],
       [0.        , 1.01505676, 0.21991545, 0.24546237]])

In [128]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.15735167, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.44930027, 0.34649884, 0.        , 0.        ],
       [0.        , 1.01505676, 0.21991545, 0.24546237]])

# Fancy Indexing

In [129]:
arr = np.empty((8,4))

for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [130]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [131]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [132]:
# Reshaping

arr = np.arange(32).reshape((8,4))

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [133]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [134]:
## ---
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [135]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [137]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [138]:
## Transpose

arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [139]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# Calculates sumes of the axis:

In [140]:
np_array_2d = np.arange(0, 6).reshape([2,3])
print(np_array_2d)
display(np.sum(np_array_2d, axis = 0)) # Vertical
display(np.sum(np_array_2d, axis = 1)) # Horizontal

[[0 1 2]
 [3 4 5]]


array([3, 5, 7])

array([ 3, 12])

# Concatenates The row axies with axis=0

In [141]:
np_array_1s = np.array([[1,1,1],[1,1,1]])
np_array_9s = np.array([[9,9,9],[9,9,9]])
display(np.concatenate([np_array_1s, np_array_9s], axis = 0))# Joins vertically
display(np.concatenate([np_array_1s, np_array_9s], axis = 1)) # Joins horizontally


array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

# Swap axes

In [142]:
import numpy as np
a = np.array([[2,3,4]])
print(a)
print()
print(np.swapaxes(a,0,1))

[[2 3 4]]

[[2]
 [3]
 [4]]


# Fast element wise array functions

In [143]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [145]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [146]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)
np.maximum(x,y)

[ 0.37462186  1.24965554  0.66539565  0.39252759  0.19231689 -0.05210091
 -0.04592605  0.76199436]
[-1.09306581 -0.93080335  0.04495701  1.59276542 -1.81320704  1.351522
 -0.04080904 -0.06684446]


array([ 0.37462186,  1.24965554,  0.66539565,  1.59276542,  0.19231689,
        1.351522  , -0.04080904,  0.76199436])

# Array oriented Programming with arrays

In [147]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) 
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) 
cond = np.array([True, False, True, True, False])
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)] 
result

[np.float64(1.1),
 np.float64(2.2),
 np.float64(1.3),
 np.float64(1.4),
 np.float64(2.5)]

In [148]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

# Mathematical and Statistical methods

In [149]:
arr = np.random.randn(5,4)
arr

array([[-0.62227451, -0.56314222,  0.75329726, -2.1043236 ],
       [-0.08431769, -1.05166743, -1.35466692,  0.13838205],
       [ 0.41806341, -0.55173557,  0.4705952 ,  1.07338358],
       [ 1.14369128, -1.01796769, -1.08306137, -0.55068893],
       [ 0.55919147,  0.86549353,  1.35056911,  0.24644747]])

In [150]:
arr.mean()

np.float64(-0.09823657931297057)

In [151]:
np.mean(arr)

np.float64(-0.09823657931297057)

In [152]:
arr.sum()

np.float64(-1.9647315862594115)

In [153]:
arr.mean(axis=1)

array([-0.63411077, -0.5880675 ,  0.35257665, -0.37700668,  0.75542539])

In [154]:
arr.sum(axis=0)

array([ 1.41435395, -2.31901938,  0.13673328, -1.19679944])

In [156]:
arr = np.arange(8)
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [157]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [158]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

# Methods for boolean arrays

In [159]:
arr = np.random.randn(100)

In [161]:
(arr > 0).sum() # Number of positive values

np.int64(44)

In [162]:
bools = np.array([False, False, True, False])
bools.any()

np.True_

In [163]:
bools.all()

np.False_

# Sorting

In [164]:
arr = np.random.randn(6)
arr

array([ 1.37782286,  1.45964687,  2.13955851,  0.50712368, -1.00346969,
        0.6029294 ])

In [165]:
arr.sort()
arr

array([-1.00346969,  0.50712368,  0.6029294 ,  1.37782286,  1.45964687,
        2.13955851])

In [166]:
# Sort in another direction

arr = np.random.randn(5,3)
arr

array([[ 0.40939097, -0.35524401,  0.42570672],
       [-0.67014989,  0.83130528, -0.31823619],
       [-0.17228086, -0.23148273,  1.88719357],
       [ 1.10048002, -1.95998939,  0.26051164],
       [-0.52275236, -1.52616365,  0.18133308]])

In [167]:
arr.sort(1)
arr

array([[-0.35524401,  0.40939097,  0.42570672],
       [-0.67014989, -0.31823619,  0.83130528],
       [-0.23148273, -0.17228086,  1.88719357],
       [-1.95998939,  0.26051164,  1.10048002],
       [-1.52616365, -0.52275236,  0.18133308]])

# Unique and other set logic

In [168]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [169]:
ints = np.array([3,3,3,2,2,1,1,4,4,])
np.unique(ints)

array([1, 2, 3, 4])

In [170]:
sorted(set(names))

[np.str_('Bob'), np.str_('Joe'), np.str_('Will')]

In [172]:
values = np.array([6,0,0,3,2,5,6])
np.isin(values,[2,3,6])

array([ True, False, False,  True,  True, False,  True])

---

In [2]:
import numpy as np
initial_array = np.ones(100).reshape(10,10)
initial_array[1:-1,1:-1] = 0
print(initial_array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
